version: '3'
services:
  pro:
    container_name: 'home_controller_app'
    build: '.'
    restart: 'always'
    ports:
      - '5000:5000'
    volumes:
      - '${LOGS_DIR}:/usr/src/home_controller_app/logs'
      - '${DATA_DIR}:/usr/src/home_controller_app/data'
      - '${CONFIG_DIR}:/usr/src/home_controller_app/config'
      - '/etc/timezone:/etc/timezone:ro'
      - '/etc/localtime:/etc/localtime:ro'
    command:
      - 'python -m flask run --host=0.0.0.0 --no-reload'
    environment:
      - 'FLASK_APP=app.py'
      - 'FLASK_ENV=production'
      - 'LOG_FILE_PATH=config/history.log'
      - 'REMOTE_REPOSITORY=${REMOTE_REPOSITORY}'
      - 'REMOTE_BRANCH=main'

# docker-compose -f docker-compose.pro.yml up --build