version: '3'
services:
  app:
    build:
      context: .
      dockerfile: DockerfileDev
    restart: 'no'
    ports:
      - '5000:5000'
    volumes:
      - './:/usr/src/home_controller_app'
      - '/etc/timezone:/etc/timezone:ro'
      - '/etc/localtime:/etc/localtime:ro'
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - LOGS_DIR=/usr/src/home_controller_app/logs
      - DATA_DIR=/usr/src/home_controller_app/data
      - CONFIG_DIR=/usr/src/home_controller_app/config
    entrypoint:
      - gunicorn 
      - --worker-class=eventlet
      - --bind=0.0.0.0:5000 
      - app:app
    tty: true

# docker-compose -f docker-compose.dev.yml up --build