"""

"""

from home_controller.rpi_pin import RpiPin
from home_controller.config import (
    MAIN_WATER_VALVE_PIN, WATER_FLOW_SENSOR_PIN, ELECTRICITY_SIGNAL_PIN,
    WATERING_PIN_0, WATERING_PIN_1, WATERING_PIN_2, WATERING_PIN_3,
    WATERING_PIN_ANY
)

MAIN_WATER_VALVE = RpiPin(MAIN_WATER_VALVE_PIN, False)
WATER_FLOW_SENSOR = RpiPin(WATER_FLOW_SENSOR_PIN, True)
ELECTRICITY_SIGNAL = RpiPin(ELECTRICITY_SIGNAL_PIN, True)

WATERING_0 = RpiPin(WATERING_PIN_0, False)
WATERING_1 = RpiPin(WATERING_PIN_1, False)
WATERING_2 = RpiPin(WATERING_PIN_2, False)
WATERING_3 = RpiPin(WATERING_PIN_3, False)
WATERING_ANY = RpiPin(WATERING_PIN_ANY, False)